[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1B5E3F"
backgroundColor = "#FDFDF8"
secondaryBackgroundColor = "#F9F9F4"
textColor = "#1A202C"
